### PR TITLE
Added ukrainian translation

### PR DESCRIPTION
**Pull request by Moonvvell**

### CODE REVIEW

**Comment by lcy0x1** [comment]
Are you able to load this project in IDEA? I have an automatic language processor that can help with translation. If so, I would recommend using that for translation instead, to help reduce unnecessary works. Otherwise, I would just merge this.

**Comment by lcy0x1** [comment]
Same for Archery

**Comment by Moonvvell** [comment]
Yes, I will use IDEA for that and recheck other files

**Comment by Moonvvell** [comment]
If i'm correctly understand you, do You mean to use this tool for automatic translation from english to ukrainian? 
Or to generate this uk_ua.json file? Isn't would be enough just to add this file that i'm added?

**Comment by Moonvvell** [comment]
Oh, I've got it. This is in test/resources, right? I've thought that this is only for tests

**Comment by lcy0x1** [comment]
I use that for non-English lang as they are hand written instead of generated. I have features like tree structure and cartesian multiplier, to help reduce the number of entries, especially for potions and potion arrows.

**Comment by Moonvvell** [comment]
There just a problem that in ukrainian language we have different endings in the verbs and adjectives based on nouns. For example Iron Axe and Iron Pickaxe - should have different translations for "Iron", that's why I'm done it manually in one file

**Pull request merged**
